version: 2
updates:
  - package-ecosystem: maven
    directory: /services
    schedule:
      interval: weekly
    groups:
      java-dependencies:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      web-dependencies:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: /services
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /web
    schedule:
      interval: weekly
