apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sentinel

resources:
  - ../../base

images:
  - name: ghcr.io/sentinel/ingest-service
    newTag: ${IMAGE_TAG}
  - name: ghcr.io/sentinel/correlation-service
    newTag: ${IMAGE_TAG}
  - name: ghcr.io/sentinel/incident-service
    newTag: ${IMAGE_TAG}
  - name: ghcr.io/sentinel/insight-service
    newTag: ${IMAGE_TAG}
  - name: ghcr.io/sentinel/web
    newTag: ${IMAGE_TAG}

patches:
  - target:
      kind: Deployment
      name: correlation-service
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 6
  - target:
      kind: ConfigMap
      name: sentinel-config
    patch: |-
      - op: replace
        path: /data/TRACE_SAMPLE_RATE
        value: "0.05"
